// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCslym3E5TdX04uh9ve6QJ6v8Y4hqnDCtk',
    appId: '1:807125399871:web:c0af42099ecc88a1097b8a',
    messagingSenderId: '807125399871',
    projectId: 'i-c-task',
    authDomain: 'i-c-task.firebaseapp.com',
    storageBucket: 'i-c-task.firebasestorage.app',
    measurementId: 'G-QHT0NZT766',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwLmg5C77kKJDwsqArUwwsVjErYykZCtE',
    appId: '1:807125399871:android:ddf3f8f070b04441097b8a',
    messagingSenderId: '807125399871',
    projectId: 'i-c-task',
    storageBucket: 'i-c-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXYf2QlPoLxVAu2jrsKKkEng6xzN8NQ5Y',
    appId: '1:807125399871:ios:f73213f84e7c9b73097b8a',
    messagingSenderId: '807125399871',
    projectId: 'i-c-task',
    storageBucket: 'i-c-task.firebasestorage.app',
    iosBundleId: 'com.example.iCTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXYf2QlPoLxVAu2jrsKKkEng6xzN8NQ5Y',
    appId: '1:807125399871:ios:f73213f84e7c9b73097b8a',
    messagingSenderId: '807125399871',
    projectId: 'i-c-task',
    storageBucket: 'i-c-task.firebasestorage.app',
    iosBundleId: 'com.example.iCTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCslym3E5TdX04uh9ve6QJ6v8Y4hqnDCtk',
    appId: '1:807125399871:web:b18185d5309eb9ed097b8a',
    messagingSenderId: '807125399871',
    projectId: 'i-c-task',
    authDomain: 'i-c-task.firebaseapp.com',
    storageBucket: 'i-c-task.firebasestorage.app',
    measurementId: 'G-P0PJRBQH9C',
  );
}
